from pathlib import Path
from quantlab_core.normalize import FIELDS, INTS, schema_for
meaning={
'agg_trade_id':'Exchange aggregate identifier','trade_id':'Individual execution identifier','price':'Executed price','quantity':'Executed base quantity','quote_quantity':'Source quote quantity','first_trade_id':'First underlying trade ID','last_trade_id':'Last underlying trade ID; range is not guaranteed to represent recoverable event timestamps','timestamp':'Exchange transaction timestamp','is_buyer_maker':'True: buyer passive, SELL aggressor; False: BUY aggressor','open_time':'Bar opening boundary','open':'First price in interval','high':'Highest price in interval','low':'Lowest price in interval','close':'Last price in interval','volume':'Base volume','close_time':'Last millisecond of interval','quote_volume':'Quote volume','number_of_trades':'Source execution count','taker_buy_base_volume':'Aggressive buy base volume','taker_buy_quote_volume':'Aggressive buy quote volume','ignore':'Source placeholder preserved; do not use as feature','create_time':'Source UTC metrics timestamp','symbol':'USD-M perpetual symbol','sum_open_interest':'Original OI base quantity level','sum_open_interest_value':'Original OI quote notional level','count_toptrader_long_short_ratio':'Top-trader account long/short ratio','sum_toptrader_long_short_ratio':'Top-trader position long/short ratio','count_long_short_ratio':'Account long/short ratio','sum_taker_long_short_vol_ratio':'Taker buy/sell volume ratio'}
lines=['# Data dictionary — schema v1','','Source numbers remain exact strings; no ingestion rounding. Integer IDs/timestamps are int64, maker flag bool. Historical timestamps are milliseconds UTC, not Spot microseconds. All source fields are non-null under accepted schema. Source column aliases are explicit in normalize.py.','']
for dataset,fields in FIELDS.items():
 lines += ['## '+dataset,'','| Field | Parquet type | Unit | Meaning | Precision / timezone | Nullable | Transformation |','|---|---|---|---|---|---|---|']
 for field in fields:
  unit='identifier' if 'id' in field else 'epoch ms' if field in ('timestamp','open_time','close_time') else 'USDT' if field in ('price','open','high','low','close','quote_quantity','quote_volume','taker_buy_quote_volume','sum_open_interest_value') else 'base asset' if field in ('quantity','volume','taker_buy_base_volume','sum_open_interest') else 'ratio' if 'ratio' in field else 'count' if field=='number_of_trades' else 'text/flag'
  lines.append(f"| {field} | {schema_for(dataset).field(field).type} | {unit} | {meaning[field]} | {'integer ms UTC' if unit=='epoch ms' else 'original lexical precision'} | no | {'integer parse' if field in INTS else 'bool parse' if field=='is_buyer_maker' else 'none'} |")
 lines+=['','Source: Binance daily '+dataset+' CSV.','']
lines+=['## Mark / index / premium candles','','Use the kline envelope. Mark/index OHLC units are USDT; premium OHLC are signed dimensionless ratios. Volume/count placeholders are retained but have no trade-volume meaning.','', '## Added fields','','| Field | Type | Unit / timezone | Nullable | Meaning / transformation |','|---|---|---|---|---|','| symbol | string | identifier | no | Partition symbol, validated for metrics |','| event_time_ms | int64 | UTC epoch ms | no | Original trade time, bar open, or parsed UTC metrics create_time |','| available_at_ms | int64 | UTC epoch ms | yes | Trade exchange time assumption; bar close+1; metrics null because historical publication unknown |','| availability_basis | string | policy label | no | Must be inspected before replay; not an observation of network latency |','','## Live envelopes','','receive_timestamp_ns: int64 local Unix UTC nanoseconds captured when message is written; not guaranteed kernel receipt time. kind: string event/control type. payload: untouched parsed JSON object; nested exchange E/T/U/u/pu/a/nq fields remain available. JSON.gz is raw capture; it is NOT normalized or admitted into the historical catalog. Connection_start/disconnect/sequence_gap/trade_gap are explicit continuity markers. Snapshot failures are errors, not snapshots.']
Path('DATA_DICTIONARY.md').write_text('\n'.join(lines)+'\n')
