symbols: [BTCUSDT, ETHUSDT, SOLUSDT]
market: Binance USD-M Futures Perpetual
start_date: '2024-10-07'
end_date: '2026-10-07'
datasets: [trades, aggTrades, klines, markPriceKlines, indexPriceKlines, premiumIndexKlines, metrics]
max_local_storage_gb: 2
remote_storage: GitHub
repository: Slimsyhalo/Trade
request_interval_seconds: 1
max_attempts: 5
